### PR TITLE
Fix triggering `clippy::mem_forget` lint in exported structs

### LINKED ISSUE #3944: `wasm-bindgen` 0.2.92 triggers `clippy::mem_forget`
### Summary

wasm-bindgen 0.2.92 triggers the Clippy rule [mem_forget](https://rust-lang.github.io/rust-clippy/master/index.html#mem_forget). Is it expected?

```shell
error: usage of `mem::forget` on `Drop` type
  --> crates/biome_wasm/src/lib.rs:24:1
   |
24 | #[wasm_bindgen]
   | ^^^^^^^^^^^^^^^
   |
   = note: argument has type `wasm_bindgen::JsValue`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mem_forget
   = note: this error originates in the attribute macro `wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by daxpedda**
I think its fine to explicitly allow certain lints.

Fixes #3944.

### CODE REVIEW

File: tests/wasm/main.rs [hunk 1]
```diff
@@ -31,6 +33,7 @@ pub mod final_;
 pub mod futures;
 pub mod gc;
 pub mod getters_and_setters;
+pub mod ignore;
```
Comment (daxpedda) [inline tests/wasm/main.rs:36]: This was missed back when it was added.

**Review by Liamolucko — APPROVED** [review]
Fair enough, we don't really need a general solution for what seems to be an isolated issue. We can always reconsider this later on if lots more issues like this show up.
