### PR TITLE
fix webpack to handle node global functions

### LINKED ISSUE #357: The 'imports::versions' test fails on OSX
I don't know why but here is the output: https://gist.github.com/kzvi/bf225ec60343397938dd5fbd97479678

OS: OSX 10.13.5 
Node: `v10.5.0` 
NPM: `6.1.0` 
rustc: `rustc 1.28.0-nightly (e3bf634e0 2018-06-28)` 
cargo: `cargo 1.28.0-nightly (e2348c2db 2018-06-07)`

### PR DESCRIPTION
**Pull request by sendilkumarn**
Closes #357

### CODE REVIEW

File: tests/all/main.rs [hunk 1]
```diff
@@ -48,6 +48,14 @@ fn project() -> Project {
                 "webpack.config.js".to_string(),
                 r#"
                 const path = require('path');
+                const fs = require('fs');
+
+                let nodeModules = {};
+                fs.readdirSync('node_modules').filter(function(x) {
+                    return ['.bin'].indexOf(x) === -1;
```
Comment (fitzgen) [inline tests/all/main.rs]: This seems like a roundabout way of saying

```js
return x !== '.bin';
```

am I misreading this?

Comment (sendilkumarn) [reply tests/all/main.rs]: yeah 😁
