### PR TITLE
Try to fix #2296 and support to get wasm file through http protocol

### LINKED ISSUE #2296: Deno target on windows error.
### Describe the Bug

When I use the deno target, there will be an error that {name}_bg.wasm cannot be found

### Steps to Reproduce

1. Run `wasm-pack build --target=deno --out-name=deno_test`
2. `import { ... } from './pkg/deno_test.js'`

### Actual Behavior

`error: Uncaught NotFound: 系统找不到指定的文件。 (os error 2)`(The system can not find the file specified)

### Additional Context
os: Windows10 19042.450 (20H2)
`import.meta.url`: file:///C:/Users/soeur/CLionProjects/deno-deno_test/pkg/deno_test.js
`const file = new URL(import.meta.url).pathname`: /C:/Users/soeur/CLionProjects/deno-deno_test/pkg/deno_test.js

### I think...
The reason for this problem is that in my case, os==windows but the separator is `/` instead of `\`, and the first character of URL.pathname is `/`

### PR DESCRIPTION
**Pull request by juzi5201314**
Fix #2296

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like the deno CI is failing though?

**Comment by juzi5201314** [comment]
> Thanks! Looks like the deno CI is failing though?

Yes, I made a stupid mistake. Now it has been fixed and passed ci.

**Comment by juzi5201314** [comment]
In deno, the usual method is to get the library directly from remote.
e.g. `import {...} from'https://deno.land/x/lib/mod.ts'`,
But `Deno.readFileSync` can only read wasm files from the local file system.
So I use `fetch` to complete the support for getting wasm files from http.

**Comment by alexcrichton** [comment]
cc @jakobhellermann mind taking a look at this?

File: crates/cli-support/src/js/mod.rs [hunk 1]
```diff
@@ -318,12 +318,29 @@ impl<'a> Context<'a> {
...
+                }}
+                wasmCode = Deno.readFileSync(file)
+            }} else if (url.protocol.includes('http')) {{
+                const wasm_url = import.meta.url.substring(0, import.meta.url.lastIndexOf('/') + 1) + '{module_name}_bg.wasm'
+                wasmCode = await (await fetch(wasm_url)).arrayBuffer()
+            }} else {{
+                console.error(`Unsupported protocol: ${{url.protocol}}`)
+                Deno.exit(0)
+            }}
+            const wasmModule = new WebAssembly.Module(wasmCode);
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:340]: You should almost never use synchronous constructors, as they can be very slow for large Wasm. Instead, use `await WebAssembly.instantiate(wasmCode, imports)`.

**Comment by zebp** [comment]
Can this get some movement? This issue makes it almost impossible to publish a Deno library that uses wasm-bindgen without modifying the generated output.

**Comment by RReverser** [comment]
I'll admit I don't fully understand the original issue. Given that Deno supports all the required Web APIs, doesn't `--target web` just work in Deno?

**Comment by zebp** [comment]
> I'll admit I don't fully understand the original issue. Given that Deno supports all the required Web APIs, doesn't `--target web` just work in Deno?

It almost works with the web target. Deno's `fetch` doesn't support fetching local files, so it can't fetch the wasm binary.

**Comment by RReverser** [comment]
> Deno's fetch doesn't support fetching local files, so it can't fetch the wasm binary.

Oh I see, that's unfortunate.

**Comment by juzi5201314** [comment]
Glad someone saw this problem.  Is there any resistance to this problem at the moment? 
 How can I help?

**Comment by zebp** [comment]
It'd be great to get some movement on this PR, this issue is a blocking one for me.

File: crates/cli-support/src/js/mod.rs (hunk 1 above)
Comment (RReverser) [reply crates/cli-support/src/js/mod.rs:340]: ^ this issue still stands. (I'm not a maintainer, but I don't think we should ever block)

File: crates/cli-support/src/js/mod.rs [hunk 2]
```diff
@@ -318,12 +318,29 @@ impl<'a> Context<'a> {
         // Deno removed support for .wasm imports in https://github.com/denoland/deno/pull/5135
         // the issue for bringing it back is https://github.com/denoland/deno/issues/5609.
         format!(
-            "const file = new URL(import.meta.url).pathname;
-            const wasmFile = file.substring(0, file.lastIndexOf(Deno.build.os === 'windows' ? '\\\\' : '/') + 1) + '{}_bg.wasm';
-            const wasmModule = new WebAssembly.Module(Deno.readFileSync(wasmFile));
+            "const url = new URL(import.meta.url)
+
+            let wasmCode = ''
+            if (url.protocol.includes('file')) {{
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:324]: Better to check protocols explicitly instead of "includes". Maybe change this to a switch-case?

File: crates/cli-support/src/js/mod.rs (hunk 1 above)
Comment (juzi5201314) [reply crates/cli-support/src/js/mod.rs]: ok! https://github.com/rustwasm/wasm-bindgen/pull/2297/commits/f71515d2c7bf601b80df832388fdabccf70b926f

File: crates/cli-support/src/js/mod.rs (hunk 2 above)
Comment (juzi5201314) [reply crates/cli-support/src/js/mod.rs]: https://github.com/rustwasm/wasm-bindgen/pull/2297/commits/4920e21c7ab857e75707b5ac305c798236267ca4

File: crates/cli-support/src/js/mod.rs [hunk 3]
```diff
@@ -341,8 +341,7 @@ impl<'a> Context<'a> {
                 console.error(`Unsupported protocol: ${{url.protocol}}`)
                 Deno.exit(0)
             }}
-            const wasmModule = new WebAssembly.Module(wasmCode);
-            const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
+            const wasmInstance = await WebAssembly.instantiate(await WebAssembly.compile(wasmCode), imports);
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:349]: You don't need `compile` separately.

```suggestion
            const wasmInstance = (await WebAssembly.instantiate(wasmCode, imports)).instance;
```

File: crates/cli-support/src/js/mod.rs [hunk 4]
```diff
@@ -322,12 +322,33 @@ impl<'a> Context<'a> {
...
+                    let file = new URL(import.meta.url).pathname;
+                    if (Deno.build.os === 'windows') {{
+                        if (file.startsWith('/')) file = file.substr(1);
+                        file = await Deno.realPath(file + '/../{module_name}_bg.wasm');
+                    }} else {{
+                        file = file.substring(0, file.lastIndexOf('/') + 1) + '{module_name}_bg.wasm';
+                    }}
+                    wasmCode = await Deno.readFile(file);
+                    break
+                case 'http:':
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:339]: I'm assuming you want it to work for `https` too?

```suggestion
                case 'http:':
                case 'https:':
```

File: crates/cli-support/src/js/mod.rs [hunk 5]
```diff
@@ -322,12 +322,33 @@ impl<'a> Context<'a> {
...
+                    const wasm_url = import.meta.url.substring(0, import.meta.url.lastIndexOf('/') + 1) + '{module_name}_bg.wasm';
+                    wasmCode = await (await fetch(wasm_url)).arrayBuffer();
+                    break
+                default:
+                    console.error(`Unsupported protocol: ${{url.protocol}}`);
+                    Deno.exit(0);
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:345]: Better to just throw an error and give a caller a chance to handle it, rather than forcefully close the program.

File: crates/cli-support/src/js/mod.rs [hunk 6]
```diff
@@ -322,12 +322,33 @@ impl<'a> Context<'a> {
...
+                    }}
+                    wasmCode = await Deno.readFile(file);
+                    break
+                case 'https:':
+                case 'http:':
+                    const wasm_url = import.meta.url.substring(0, import.meta.url.lastIndexOf('/') + 1) + '{module_name}_bg.wasm';
+                    wasmCode = await (await fetch(wasm_url)).arrayBuffer();
+                    break
+                default:
+                    throw `Unsupported protocol: ${{url.protocol}}`;
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:345]: Throwing strings is a bad practice, since they don't have any stacktrace attached. Best to throw a proper `Error` instance:

```suggestion
                    throw new Error(`Unsupported protocol: ${{url.protocol}}`);
```

File: crates/cli-support/src/js/mod.rs [hunk 7]
```diff
@@ -322,12 +322,33 @@ impl<'a> Context<'a> {
...
-            "const file = new URL(import.meta.url).pathname;
-            const wasmFile = file.substring(0, file.lastIndexOf(Deno.build.os === 'windows' ? '\\\\' : '/') + 1) + '{}_bg.wasm';
-            const wasmModule = new WebAssembly.Module(Deno.readFileSync(wasmFile));
-            const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
+            "const url = new URL(import.meta.url);
+
+            let wasmCode = '';
+            switch (url.protocol) {{
+                case 'file:':
+                    let file = new URL(import.meta.url).pathname;
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:330]: You already have `url` instance from above:

```suggestion
                    let file = url.pathname;
```

File: crates/cli-support/src/js/mod.rs [hunk 8]
```diff
@@ -322,12 +322,33 @@ impl<'a> Context<'a> {
...
+                        if (file.startsWith('/')) file = file.substr(1);
+                        file = await Deno.realPath(file + '/../{module_name}_bg.wasm');
+                    }} else {{
+                        file = file.substring(0, file.lastIndexOf('/') + 1) + '{module_name}_bg.wasm';
+                    }}
+                    wasmCode = await Deno.readFile(file);
+                    break
+                case 'https:':
+                case 'http:':
+                    const wasm_url = import.meta.url.substring(0, import.meta.url.lastIndexOf('/') + 1) + '{module_name}_bg.wasm';
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:341]: It's more reliable to use real URL resolution instead of string manipulation. You can probably reuse this code: https://github.com/rustwasm/wasm-bindgen/blob/8594cae64b435cb5ab4d5233336fd15b3cb8cec2/crates/cli-support/src/js/mod.rs#L648

File: crates/cli-support/src/js/mod.rs [hunk 9]
```diff
@@ -322,12 +322,33 @@ impl<'a> Context<'a> {
...
+
+            let wasmCode = '';
+            switch (url.protocol) {{
+                case 'file:':
+                    let file = new URL(import.meta.url).pathname;
+                    if (Deno.build.os === 'windows') {{
+                        if (file.startsWith('/')) file = file.substr(1);
+                        file = await Deno.realPath(file + '/../{module_name}_bg.wasm');
+                    }} else {{
+                        file = file.substring(0, file.lastIndexOf('/') + 1) + '{module_name}_bg.wasm';
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:335]: Same here about URL manipulation.

File: crates/cli-support/src/js/mod.rs [hunk 10]
```diff
@@ -322,12 +322,33 @@ impl<'a> Context<'a> {
...
-            const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
+            "const url = new URL(import.meta.url);
+
+            let wasmCode = '';
+            switch (url.protocol) {{
+                case 'file:':
+                    let file = new URL(import.meta.url).pathname;
+                    if (Deno.build.os === 'windows') {{
+                        if (file.startsWith('/')) file = file.substr(1);
+                        file = await Deno.realPath(file + '/../{module_name}_bg.wasm');
```
Comment (RReverser) [inline crates/cli-support/src/js/mod.rs:333]: Why do we use `../` on Windows but not elsewhere?

File: crates/cli-support/src/js/mod.rs (hunk 8 above)
Comment (juzi5201314) [reply crates/cli-support/src/js/mod.rs]: Sorry and thank you.
I'm a newbie, I didn't know that URL has this kind of usage before this. So some codes used bad methods to try to get the `_bg.wasm` file in the same directory.
Now the code has become clean🎉

**Comment by RReverser** [comment]
@juzi5201314 Didn't see the updates following the last round of reviews, thanks, code looks a lot better!
