### PR TITLE
Replace all `Self` identifiers in method argument and return types

### LINKED ISSUE #3105: Returning Option<Self> in #[wasm_bindgen] impl block gives error
### Summary

This may not be the best example, but for simplicity I am adapting the code from this [issue](https://github.com/rustwasm/wasm-bindgen/issues/137). The problem is as follows:

The following return types work for `new` with the `#[wasm_bindgen]` attribute applied to the impl: `Universe`, `Self`, `Option<Universe>`. However, this return type appears not to work: `Option<Self>`. Is there some deep reason for this, or is this potentially a bug?

```rust
extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Cell {
    Dead = 0,
    Alive = 1,
}

#[wasm_bindgen]
pub struct Universe {
    width: u32,
    height: u32,
    cells: Vec<Cell>,
}

/// Public methods, exported to JavaScript.
#[wasm_bindgen]
impl Universe {
    // The tutorial has the signature:
    // pub fn new() -> Universe {
    // This signature works:
    // pub fn new() -> Option<Universe> {
    pub fn new() -> Option<Self> {
        let width = 128;
        let height = 128;

        let cells = (0..width * height)
            .map(|i| {
                if i % 2 == 0 || i % 7 == 0 {
                    Cell::Alive
                } else {
                    Cell::Dead
                }
            })
            .collect();

        Some(Self {
            width,
            height,
            cells,
        })
    }
}
```

This gives the error:

```
error[E0401]: can't use generic parameters from outer function
   --> src\lib.rs:177:28
    |
139 | impl Universe {
    | ---- `Self` type implicitly declared here, by this `impl`
...
177 |     pub fn new() -> Option<Self> {
    |                            ^^^^
    |                            |
    |                            use of generic parameter from outer function
    |                            use a type here instead
```

The same problem arises when attempting to use `Self` with `Result` and other generics.

### PR DESCRIPTION
**Pull request by RunDevelopment**
fixes #3105
closes #3631

This PR is based on #3631 by @snOm3ad. I looked at it to see what needed to be changed and that I stole tests from there. I tagged @snOm3ad as the co-author in one commit, but (*speaking to the maintainer*) please also tag them in the merge commit of this PR in case GH doesn't.

The main approach of this PR is different from #3631. I used [`syn`'s mut visitor](https://docs.rs/syn/latest/syn/visit_mut/index.html) to replace all `Self` identifiers with the identifier for the type. This makes the code very simple and guarantees that no occurrences of `Self` are left.

### CODE REVIEW

**Review by daxpedda — COMMENTED** [review]
I would appreciate if you could leave some code comments here, I always have to spend non-trivial time digging into this when it comes up.

File: crates/macro-support/src/parser.rs [hunk 1]
```diff
@@ -911,24 +912,24 @@ fn function_from_decl(
...
+                    if i == "Self" {
+                        *i = self.0.clone();
+                    }
+                }
+            }
+
+            let mut replace = SelfReplace(self_ty.clone());
+            replace.visit_type_mut(&mut t);
+        }
+        t
```
Comment (daxpedda) [inline crates/macro-support/src/parser.rs:932]: Apologies, I wasn't being specific enough.
This is the part I think that needs to be explained.

Whats happening here?
How is this used to replace all `Self` regardless of depth? (is that the case?)
Why is `VisitMut` necessary?

This might need more comments in the surrounding code as well.
You didn't write all the surrounding code, I'm sorry this is being pushed onto you!

Comment (RunDevelopment) [reply crates/macro-support/src/parser.rs:932]: Ah, sorry about that. I did **a lot** of stuff with ASTs before, so using visitors is almost second nature to me at this point.

I'll add some more comments to answer your questions.

> You didn't write all the surrounding code, I'm sorry this is being pushed onto you!

No worries. I'm currently working on another PR that changes some code in this area, so I can add a few comments to explain the big picture and how all the pieces for together.

Comment (RunDevelopment) [reply crates/macro-support/src/parser.rs]: Okay, I added a few comments **for now**.

I actually wrote a few more, but discovered some minor bugs while doing that. So I'll fix those bugs and explain the fixed code in a follow-up PR.

**Review by daxpedda — APPROVED** [review]
Thank you!
(needs a rebase again)
